<?php


namespace app\admin;


use app\BaseController;
use app\middleware\Auth;
use app\middleware\Before;
use app\middleware\Role;

class UserBaseController extends BaseController
{
    protected $middleware = [Auth::class,Role::class,Before::class,];//验证token和访问控制器权利
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}