<?php

namespace app\admin\controller\user;

use app\admin\controller\Base;
use app\common\model\RealName as models;

class RealName extends Base
{
    protected $model;

    /**
     * 身份证控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $list = $this->model->withJoin([
            'user' => ['user_name']
        ])->order('id desc')->paginate(['list_rows' => $limit, 'page' => $page]);

        return $this->success($list);
    }
}