<?php


namespace app\admin\controller\auth;

use app\admin\controller\Base;

use think\facade\Db;

class RoleMenu extends Base
{
    protected $model;

    /**
     * 角色菜单控制器
     */
    public function initialize()
    {
        $this->model = new \app\common\model\RoleMenu();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        $list = Db::name('common_admin_role_menu')->alias('a')
            ->field('a.*,b.name,b.status')
            ->join('common_admin_role b', 'a.role_id=b.id')
            ->select();

        return $this->success($list);
    }

    /**
     * 添加
     */
    public function add()
    {
        //过滤数据
        $postField = 'role_id,auth_ids';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        $user = $this->model->where('role_id', $post['role_id'])->find();
        if ($user) return $this->failed('该权限已存在');

        $save = $this->model->save($post);
        if ($save) return $this->success([]);
        return $this->failed('新增失败');
    }

    /**
     * 修改
     * @return mixed
     */
    public function edit()
    {
        //过滤数据
        $postField = 'id,role_id,auth_ids';
        $post = $this->request->only(explode(',', $postField), 'post', null);

        if (!isset($post['id']) || $post['id']<1) return $this->failed('ID不存在');

        //查询是否重复的该菜单
        $find = $this->model->where('role_id', $post['role_id'])->where('id', '<>', $post['id'])->find();
        if ($find) return $this->failed('该权限已存在');

        //执行修改数据
        $save = $this->model->update($post);
        if ($save) return $this->success([]);
        return $this->failed('修改失败');
    }
}