<?php

namespace app\admin\controller\count;


use app\admin\controller\Base;
use app\common\model\OrderModel;

class Order extends Base
{
    protected $model;

    /**
     * 订单控制器
     */
    public function initialize()
    {
        $this->model = new OrderModel();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //今日订单量和订单量统一 未排除未支付的
    public function index()
    {
        $today = $this->model->whereTime('create_time', 'today')->count();
        $total = $this->model->count();
        return $this->success(['today' => $today, 'total' => $total]);
    }

    //today 今日订单量 未排除未支付的
    public function today_order()
    {
        $total = $this->model->whereTime('create_time', 'today')->count();
        return $this->success(['today' => $total]);
    }

    //today 今日订单量 未排除未支付的
    public function total_order()
    {
        $total = $this->model->count();
        return $this->success(['today' => $total]);
    }

    //today 今日订单量 排除未支付的
    public function today_pay_order()
    {
        $total = $this->model->where('pay_status', $this->model::PAY_OK)->whereTime('create_time', 'today')->count();
        return $this->success(['today' => $total]);
    }

    //总订单量 排除未支付的
    public function total_pay_order()
    {
        $total = $this->model->where('pay_status', $this->model::PAY_OK)->count();
        return $this->success(['total' => $total]);
    }

    //今日支付订单金额  已支付的
    public function today_pay()
    {
        $total = $this->model->where('pay_status', $this->model::PAY_OK)->whereTime('create_time', 'today')->sum('pay_price');
        return $this->success(['total' => $total]);
    }

    //总支付订单金额 已支付的
    public function total_pay()
    {
        $total = $this->model->where('pay_status', $this->model::PAY_OK)->sum('pay_price');
        return $this->success(['total' => $total]);
    }
}