<?php

namespace app\admin\controller\count;


use app\admin\controller\Base;
use app\common\model\PayRecharge;

class Recharge extends Base
{
    protected $model;

    /**
     * 充值控制器
     */
    public function initialize()
    {
        $this->model = new PayRecharge();
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    //今日充值和总充值统一
    public function index()
    {
        $today = $this->model->whereNotNull('success_time')->whereTime('success_time', 'today')->sum('money');
        $total = $this->model->whereNotNull('success_time')->sum('money');
        return $this->success(['today' => $today, 'total' => $total]);
    }

    //today 今日充值
    public function today_recharge()
    {
        $total = $this->model->whereNotNull('success_time')->whereTime('success_time', 'today')->sum('money');
        return $this->success(['today' => $total]);
    }

    //总充值
    public function total_recharge()
    {
        $total = $this->model->whereNotNull('success_time')->sum('money');
        return $this->success(['total' => $total]);
    }
}