<?php

namespace app\admin\controller\count;


use app\admin\controller\Base;
use app\common\model\User;

class Register extends Base
{
    protected $model;

    /**
     * 充值控制器
     */
    public function initialize()
    {
        $this->model = new User();
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    //今日注册和总注册统一
    public function index()
    {
        $today =$this->model->whereTime('create_time','today')->count();
        $total = $this->model->count();
        return $this->success(['today'=>$today,'total'=>$total]);
    }

    //today 今日注册
    public function today_register()
    {
        $total =$this->model->whereTime('create_time','today')->count();
        return $this->success(['today'=>$total]);
    }

    //总注册
    public function total_register()
    {
        $total = $this->model->count();
        return $this->success(['total'=>$total]);
    }
}