<?php

namespace app\admin\controller\count;


use app\admin\controller\Base;
use app\common\model\PayWithdraw;

class Withdrawal extends Base
{
    protected $model;

    /**
     * 提现控制器
     */
    public function initialize()
    {
        $this->model = new PayWithdraw();
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    //今日提现和总提现
    public function index()
    {
        $today =$this->model->where('status',1)->whereTime('success_time','today')->sum('money');
        $total = $this->model->where('status',1)->sum('money');
        return $this->success(['today'=>$today,'total'=>$total]);
    }

    //today 今日提现
    public function today_withdrawal()
    {
        $total =$this->model->where('status',1)->whereTime('success_time','today')->sum('money');
        return $this->success(['today'=>$total]);
    }

    //总提现
    public function total_withdrawal()
    {
        $total = $this->model->where('status',1)->sum('money');
        return $this->success(['total'=>$total]);
    }
}