<?php


namespace app\admin\controller\log;


use app\admin\controller\Base;
use app\common\model\AdminLog as models;

class AdminLog extends Base
{
    protected $model;

    /**
     * 后台操作控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {
        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件

        //没办法区分type
        $list =$this->model->order('id desc')->paginate(['list_rows'=>$limit,'page'=>$page]);;

        return $this->success($list);
    }
}