<?php


namespace app\admin\controller\log;


use app\admin\controller\Base;
use app\common\model\MoneyLog as models;

class MoneyLog extends Base
{
    protected $model;

    /**
     * 资金流动控制器
     */
    public function initialize()
    {
        $this->model = new models();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 列表
     */
    public function index()
    {

        //当前页
        $page = $this->request->post('page', 1);
        //每页显示数量
        $limit = $this->request->post('limit', 10);
        //查询搜索条件
        $post = $this->request->post();
        $map =[];

        isset($post['status']) && $post['status']!='' && $map[]= ['a.status','=',$post['status']]; // 资金用途
        isset($post['type']) && $post['type']!='' && $map[]= ['a.type','=',$post['type']]; // 大类型 收支 什么的
        // isset($post['money_type'])&& $post['money_type']!='' && $map[]= ['a.money_type','=',$post['money_type']]; // 钱的类型
        isset($post['user_id']) && $post['user_id']!='' && $map[]= ['uid','=',$post['user_id']]; // 用户ID
        isset($post['search_mark']) && $post['search_mark']!='' && $map[]= ['mark','like','%'.$post['search_mark'].'%']; // 备注查询
        isset($post['user_phone']) && $post['user_phone']!='' && $map[]= ['b.phone', 'like', '%' . $post['user_phone'] . '%']; // 用户名 模糊查询
        $order = 'a.id desc';
        isset($post['create_time_sort'])&& $order='a.id '.$post['create_time_sort'];

        $list =$this->model->page_list($map,$limit,$page,$order);
        return $this->success($list);
    }
}